
name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: |
          npm install
          npm install @capacitor/core @capacitor/cli @capacitor/android

      - name: Build Web Assets
        run: npm run build

      - name: Initialize Capacitor Android
        # We run this every time in CI to ensure a fresh android folder
        run: |
          npx cap add android
          npx cap sync

      - name: Build Debug APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: AmazCRM-App
          path: android/app/build/outputs/apk/debug/app-debug.apk
